core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login as user_login
from django.conf import settings

from core.views import (
    permission_denied_view,
    page_not_found,
    server_error,
    gateway_timeout
)
from core.views import user_logout

handler403 = permission_denied_view
handler404 = page_not_found
handler500 = server_error
handler504 = gateway_timeout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^user-login/$', user_login, {
            'template_name': 'login_form.html',
            'redirect_field_name': 'next'
        }, name='user-login-form'),

    url(r'^logout/$', user_logout, {
            'login_url': '/'
        }, name='logout'),

    url(r'^', include('inventory.urls'),
        name="home"),
    ]

if settings.DEBUG:
    urlpatterns += [
        # test error pages urls
        url(r'^404/', handler404),
        url(r'^403/', handler403),
        url(r'^500/', handler500),
        url(r'^504/', handler504),
    ]

inventory/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required

from .views import (
    DroneView,
    DroneAddView,
    DroneUpdateView,
    DroneDeleteView,
    CameraView,
    CameraAddView,
    CameraUpdateView,
    CameraDeleteView,
    BrandView,
    BrandUpdateView,
    BrandDeleteView,
)


urlpatterns = [
    url(r'^$',
        DroneView.as_view(),
        name="inventory-drone-list"),

    url(r'drone/add/$',
        permission_required('inventory.add_drone')(DroneAddView.as_view()),
        name="inventory-drone"),

    url(r'drone/(?P<pk>[0-9]+)/$',
        permission_required('inventory.change_drone')(DroneUpdateView.as_view()),
        name="inventory-drone-update"),

    url(r'drone/(?P<pk>[0-9]+)/delete/$',
        permission_required('inventory.delete_drone')(DroneDeleteView.as_view()),
        name="inventory-drone-delete"),

    url(r'^camera/$',
        CameraView.as_view(),
        name="inventory-camera-list"),

    url(r'camera/add/$',
        permission_required('inventory.add_camera')(CameraAddView.as_view()),
        name="inventory-camera"),

    url(r'camera/(?P<pk>[0-9]+)/$',
        permission_required('inventory.change_camera')(CameraUpdateView.as_view()),
        name="inventory-camera-update"),

    url(r'camera/(?P<pk>[0-9]+)/delete/$',
        permission_required('inventory.delete_camera')(CameraDeleteView.as_view()),
        name="inventory-drone-delete"),

    url(r'brand/$',
        permission_required('inventory.add_brand')(BrandView.as_view()),
        name="inventory-brand"),

    url(r'brand/(?P<pk>[0-9]+)/$',
        permission_required('inventory.change_brand')(BrandUpdateView.as_view()),
        name="inventory-brand-update"),

    url(r'brand/(?P<pk>[0-9]+)/delete/$',
        permission_required('inventory.delete_brand')(BrandDeleteView.as_view()),
        name="inventory-brand-delete"),
]

inventory/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Brand(models.Model):
    """Brand of drone or camera"""
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return '{0}'.format(self.name)

    def get_absolute_url(self):
        return reverse('inventory-brand-update', kwargs={'pk': self.pk})

    def num_linked(self):
        return self.drones.count() + self.cameras.count()


class Camera(models.Model):
    """Camera for drone"""
    model = models.CharField(max_length=200, unique=True)
    brand = models.ForeignKey(Brand, related_name='cameras', null=True)
    megapixel = models.FloatField()

    def __unicode__(self):
        return '{0} - {1}'.format(self.model, self.brand)

    def get_absolute_url(self):
        return reverse('inventory-camera-update', kwargs={'pk': self.pk})

    def num_of_drone(self):
        return self.drones.count()


class Drone(models.Model):
    """Drone registered"""
    model = models.CharField(max_length=200, unique=True)
    brand = models.ForeignKey(Brand, related_name='drones', null=True)
    serial_number = models.CharField(max_length=20)
    added_date = models.DateTimeField('date added', default=timezone.now)
    cameras = models.ManyToManyField(Camera, related_name='drones', blank=True)

    class Meta:
        ordering = ['brand']

    def __unicode__(self):
        return '{0} - {1}'.format(self.model, self.brand)

    def get_absolute_url(self):
        return reverse('inventory-drone-update', kwargs={'pk': self.pk})

inventory/forms.py
from django import forms

from .models import Brand, Camera, Drone


class DroneForm(forms.ModelForm):

    cameras = forms.ModelMultipleChoiceField(
        label="Compatible Camera's",
        widget=forms.CheckboxSelectMultiple(),
        required=False,
        queryset=Camera.objects.all())

    class Meta:
        model = Drone
        exclude = ['added_date']


class CameraForm(forms.ModelForm):
    class Meta:
        model = Camera
        fields = '__all__'


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

inventory/views.py
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Drone, Camera, Brand
from .forms import DroneForm, CameraForm, BrandForm


class DroneView(ListView):
    model = Drone
    template_name = 'inventory/drone_list.html'


class DroneAddView(SuccessMessageMixin, CreateView):
    template_name = 'inventory/drone_add_form.html'
    form_class = DroneForm
    success_url = reverse_lazy('inventory-drone-list')
    success_message = "Drone '%(model)s' was added successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            model=self.object.model,
        )

    def form_valid(self, form):
        return super(DroneAddView, self).form_valid(form)


class DroneUpdateView(SuccessMessageMixin, UpdateView):
    template_name_suffix = '_update_form'
    model = Drone
    form_class = DroneForm
    success_url = reverse_lazy('inventory-drone-list')
    success_message = "Drone '%(model)s' was updated successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            model=self.object.model,
        )

    def form_valid(self, form):
        return super(DroneUpdateView, self).form_valid(form)


class DroneDeleteView(DeleteView):
    model = Drone
    success_url = reverse_lazy('inventory-drone-list')
    success_message = "Drone '%(model)s' was deleted successfully"


class CameraView(ListView):
    model = Camera
    template_name = 'inventory/camera_list.html'


class CameraAddView(SuccessMessageMixin, CreateView):
    template_name = 'inventory/camera_add_form.html'
    form_class = CameraForm
    success_url = reverse_lazy('inventory-camera-list')
    success_message = "Camera '%(model)s' was added successfully"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            model=self.object.model,
        )

    def form_valid(self, form):
        return super(CameraView, self).form_valid(form)


class CameraUpdateView(SuccessMessageMixin, UpdateView):
    template_name_suffix = '_update_form'
    model = Camera
    form_class = CameraForm
    success_url = reverse_lazy('inventory-camera-list')
    success_message = "Camera '%(model)s' was updated successfully"

    def get_context_data(self, **kwargs):
        context = super(CameraUpdateView, self).get_context_data(**kwargs)
        context['object_list'] = Camera.objects.all()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            model=self.object.model,
        )

    def form_valid(self, form):
        return super(CameraUpdateView, self).form_valid(form)


class CameraDeleteView(DeleteView):
    model = Camera
    success_url = reverse_lazy('inventory-camera-list')
    success_message = "Camera '%(model)s' was deleted successfully"


class BrandView(SuccessMessageMixin, CreateView):
    template_name = 'inventory/brand.html'
    form_class = BrandForm
    success_url = reverse_lazy('inventory-brand')
    success_message = "Drone '%(name)s' was added successfully"

    def get_context_data(self, **kwargs):
        context = super(BrandView, self).get_context_data(**kwargs)
        context['object_list'] = Brand.objects.all()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            name=self.object.name,
        )

    def form_valid(self, form):
        return super(BrandView, self).form_valid(form)


class BrandUpdateView(SuccessMessageMixin, UpdateView):
    template_name_suffix = '_update_form'
    model = Brand
    form_class = BrandForm
    success_url = reverse_lazy('inventory-brand')
    success_message = "Brand '%(name)s' was updated successfully"

    def get_context_data(self, **kwargs):
        context = super(BrandUpdateView, self).get_context_data(**kwargs)
        context['object_list'] = Brand.objects.all()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            model=self.object.name,
        )

    def form_valid(self, form):
        return super(BrandUpdateView, self).form_valid(form)


class BrandDeleteView(DeleteView):
    model = Brand
    success_url = reverse_lazy('inventory-brand')
    success_message = "Brand '%(model)s' was deleted successfully"

templates/inventory/brand.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Add new brand</h2>
            <form action="{% url "inventory-brand" %}" method="post">{% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
        {% include "inventory/include/brand_list.html" %}
        <div class="spacer-lg"></div>
    </div>
</div>
{% endblock extend_base %}

templates/inventory/brand_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Are you sure?</h2>
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete the brand &laquo;<strong>{{ object }}</strong>&raquo;?</p>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Yes, I'm sure</button>
                    <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">No, take me back</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/brand_update_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Edit a brand</h2>
            <form action="" method="post">
                {% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
        {% include "inventory/include/brand_list.html" %}
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/camera_add_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Add new camera</h2>
            <form action="{% url "inventory-camera" %}" method="post">{% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">Cancel</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/camera_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Are you sure?</h2>
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete the camera &laquo;<strong>{{ object }}</strong>&raquo;?</p>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Yes, I'm sure</button>
                    <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">No, take me back</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/camera_list.html
{% extends 'base.html' %}
{% load staticfiles sekizai_tags bootstrap3 %}

{% block extend_base %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'css/theme.bootstrap.min.css' %}">{% endaddtoblock %}

<div class="container">
    {% with 1 as camera_inventory %}
    {% include "inventory/include/header.html" %}
    {% endwith %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
            <table class="table table-sorter">
                <thead>
                    <th class="sorter-false filter-false">#</th>
                    <th>Model</th>
                    <th class="filter-select filter-exact" data-placeholder="Pick a brand">Brand</th>
                    <th>Megapixel</th>
                    {% if user.is_authenticated %}<th class="sorter-false"></th>{% endif %}
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.id }}</td>
                    <td>{{ object.model }}</td>
                    <td>{{ object.brand }}</td>
                    <td>{{ object.megapixel }}</td>
                    {% if user.is_authenticated %}<td class="text-center">
                        <a role="button" href="{{ object.get_absolute_url }}"><span class="badge alert-success">{% bootstrap_icon "pencil" %} Edit</span></a>
                        
                        {% if object.num_of_drone == 0 %}<a role="button" href="{{ object.get_absolute_url }}delete/"><span class="badge alert-danger">{% bootstrap_icon "trash" %} Remove</span></a>{% endif %}
                    </td>{% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>

{% addtoblock "js" %}<script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{% static 'js/jquery.tablesorter.widgets.min.js' %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}
<script>
$(function() {

    $("table.table-sorter").tablesorter({
        theme : 'bootstrap',
        widthFixed: false,
        headerTemplate : '{content} {icon}',
        widgets : ['uitheme', 'filter', 'zebra'],

        widgetOptions : {
            zebra : ["even", "odd"],
            filter_reset : ".reset",
            filter_cssFilter: "form-control"
        }
    });

    $('.tablesorter-filter-row').find('td:first-child').html('');
    {% if user.is_authenticated %}$('.tablesorter-filter-row').find('td:last-child').html('');{% endif %}
});
</script>
{% endaddtoblock %}

{% endblock extend_base %}

templates/inventory/camera_update_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Edit a camera</h2>
            <form action="" method="post">{% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">Cancel</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/drone_add_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Add new drone</h2>
            <form action="{% url "inventory-drone" %}" method="post">{% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">Cancel</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/drone_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}
<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Are you sure?</h2>
            <form action="" method="post">{% csrf_token %}
                <p>Are you sure you want to delete the drone &laquo;<strong>{{ object }}</strong>&raquo;?</p>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Yes, I'm sure</button>
                    <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">No, take me back</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>
{% endblock extend_base %}

templates/inventory/drone_list.html
{% extends 'base.html' %}
{% load staticfiles sekizai_tags bootstrap3 %}

{% block extend_base %}

{% addtoblock "css" %}<link rel="stylesheet" href="{% static 'css/theme.bootstrap.min.css' %}">{% endaddtoblock %}

<div class="container">
    {% with 1 as drone_inventory %}
    {% include "inventory/include/header.html" %}
    {% endwith %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
            <table class="table table-sorter">
                <thead>
                    <th class="sorter-false filter-false">#</th>
                    <th>Name</th>
                    <th class="filter-select filter-exact" data-placeholder="Pick a brand">Brand</th>
                    <th>SN</th>
                    <th>Compatible camera(s)</th>
                    {% if user.is_authenticated %}<th class="sorter-false"></th>{% endif %}
                </thead>
                <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.id }}</td>
                    <td>{{ object.model }}</td>
                    <td>{{ object.brand }}</td>
                    <td>{{ object.serial_number }}</td>
                    <td>
                    {% for camera in object.cameras.all %}
                        {{ camera.model }}, {{ camera.brand }}, {{ camera.megapixel|floatformat:"-1"}} MP{% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
                    </td>
                    {% if user.is_authenticated %}<td class="text-center">
                        <a role="button" href="{{ object.get_absolute_url }}"><span class="badge alert-success">{% bootstrap_icon "pencil" %} Edit</span></a>
                        
                        <a role="button" href="{{ object.get_absolute_url }}delete/"><span class="badge alert-danger">{% bootstrap_icon "trash" %} Remove</span></a>
                    </td>{% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>

{% addtoblock "js" %}<script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{% static 'js/jquery.tablesorter.widgets.min.js' %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}
<script>
$(function() {

    $("table.table-sorter").tablesorter({
        theme : 'bootstrap',
        widthFixed: false,
        headerTemplate : '{content} {icon}',
        widgets : ['uitheme', 'filter', 'zebra'],

        widgetOptions : {
            zebra : ["even", "odd"],
            filter_reset : ".reset",
            filter_cssFilter: "form-control"
        }
    });

    $('.tablesorter-filter-row').find('td:first-child').html('');
    {% if user.is_authenticated %}$('.tablesorter-filter-row').find('td:last-child').html('');{% endif %}
});
</script>
{% endaddtoblock %}

{% endblock extend_base %}

templates/inventory/drone_update_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block extend_base %}

<div class="container">
    {% include "inventory/include/header.html" %}
    <div class="spacer"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Edit a drone</h2>
            <form action="" method="post">{% csrf_token %}
                <fieldset>
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="submit" class="btn btn-default" onclick="javascript:window.history.back();return false;">Cancel</button>
                    {% endbuttons %}
                </fieldset>
            </form>
        </div>
    </div>
    <div class="spacer-lg"></div>
</div>

{% endblock extend_base %}